name = "TsyganenkoModels"
uuid = "14dfbe45-703c-4bf3-b096-15691adbb981"
version = "1.0.0-DEV"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[workspace]
projects = ["docs", "test"]

[deps]
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GeoCotrans = "4624b3bc-fe35-44f8-bfa8-722ff9c0e307"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Bumper = "0.7"
Dates = "1"
GeoCotrans = "0.1.4"
LinearAlgebra = "1"
SpecialFunctions = "2"
julia = "1.10"
