name = "TsyganenkoModels"
uuid = "14dfbe45-703c-4bf3-b096-15691adbb981"
version = "1.0.0-DEV"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[deps]
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
GeoCotrans = "4624b3bc-fe35-44f8-bfa8-722ff9c0e307"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
Bumper = "0.7.1"
GeoCotrans = "0.1.3"
SpecialFunctions = "2"
julia = "1.10"
